### ISSUE TITLE
Authorized Web API calls hangs 

### ISSUE THREAD

**Issue by rarobe** [AzureADQuickStarts/AppModelv2-WebAPI-DotNet#1]
I have implemented the AppModelv2 on a WebAPI (as per this sample) deployed to a WebRole on Azure.

It all works fine for 4 - 5 days, then all API requests with an Authorization Bearer token will hang indefinitely; anonymous requests continue to work successfully. 

Rebooting the web role server fixes the issue, and api requests with Authorization Bearer tokens will work again for another 4 – 5 days before they start hanging (& failing) again.

**Comment by jmprieur** [comment]
Moving to "https://github.com/AzureADQuickStarts/AppModelv2-NativeClient-DotNet" which is really the same sample
