### ISSUE TITLE
Update to use MSAL

### ISSUE THREAD

**Issue by dstrockis** [AzureADQuickStarts/AppModelv2-WebAPI-DotNet#2]
This tutorial currently uses an outdated, unsupported client library, `Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory` (ADAL Experimental).  We are working on updating this tutorial to the `Microsoft.Identity.Client` preview library (MSAL). In the meantime, we recommend replacing the usage of ADAL Experimental in this tutorial with MSAL.  More information on your options in choosing a client library is available in our [limitations article](active-directory-v2-limitations.md).

**Comment by danieldobalian** [comment]
Resolved with following PR's:
[Completed Code](https://github.com/AzureADQuickStarts/AppModelv2-WebAPI-DotNet/pull/3)
[Skeleton Code](https://github.com/AzureADQuickStarts/AppModelv2-WebAPI-DotNet/pull/4)
